import React, { useEffect, useState } from 'react';

const GUIDE = '/guide';
const pagePath = (slug) => slug === 'home' ? GUIDE : GUIDE + '/' + slug;

const pages = [
  { slug: 'home', title: 'Home', eyebrow: 'First Car Guide', summary: 'Everything you need to make your first car decision with confidence.', icon: 'home', accent: 'mint' },
  { slug: 'mistakes', title: 'The Top 10 Mistakes', eyebrow: 'Learn the traps', summary: 'The common first-car mistakes that can cost you more than expected.', icon: 'warning', accent: 'yellow' },
  { slug: 'buying-smart', title: 'Buying Smart', eyebrow: 'Plan your money', summary: 'See the real cost of owning a car, from the first payment to the hidden extras.', icon: 'cart', accent: 'lilac' },
  { slug: 'protect-yourself', title: 'Protect Yourself', eyebrow: 'Know your rights', summary: 'Compare sellers, check the history and know what help is available.', icon: 'shield', accent: 'blue' },
  { slug: 'insurance', title: 'Insurance Explained', eyebrow: 'Choose your cover', summary: 'Understand the main types of motor vehicle insurance and what changes your premium.', icon: 'document', accent: 'peach' },
  { slug: 'sources', title: 'Sources & Credits', eyebrow: 'Go further', summary: 'The official sources and visual credits behind this classroom project.', icon: 'book', accent: 'mint' },
];

const mistakes = [
  ['Spending every dollar of your savings', 'A car costs more than its purchase price. Registration, insurance, fuel and repairs start immediately.', 'You may have no emergency buffer when something goes wrong.', 'Set a maximum price that leaves room for the first year of running costs.'],
  ['Forgetting the ongoing costs', 'Fuel, tyres, servicing and registration vary widely between vehicles.', 'A cheap car can become a weekly budget squeeze.', 'Write down your weekly, monthly and yearly estimates before comparing cars.'],
  ['Choosing appearance over reliability', 'A shiny body or great sound system cannot show how the engine, brakes or transmission are performing.', 'Cosmetic excitement can hide expensive mechanical work.', 'Prioritise safety, history, condition and a trusted inspection.'],
  ['Not comparing prices', 'One listing does not show the market value of similar vehicles.', 'You can overpay and leave less money for insurance and repairs.', 'Compare age, kilometres, condition and features across several listings.'],
  ['Skipping an independent inspection', 'A test drive cannot identify every mechanical issue.', 'You could inherit faults that cost thousands to fix.', 'Pay for an independent pre-purchase inspection before you commit.'],
  ['Ignoring the vehicle history', 'A check can reveal finance owing, stolen status, written-off records and odometer concerns.', 'The car may be unsafe, hard to insure or difficult to resell.', 'Run a PPSR check, match the VIN and check the paperwork.'],
  ['Picking the wrong insurance', 'Different policies protect different things, and the cheapest premium may leave big gaps.', 'A crash, theft or storm can leave you paying a large bill yourself.', 'Compare cover, excess, exclusions and market or agreed value.'],
  ['Not understanding your consumer rights', 'Dealer and private sales do not have the same protections.', 'You may miss a chance to seek a remedy for a serious problem.', 'Read the contract and learn the rules in your state or territory.'],
  ['Rushing because you feel pressure', 'Urgency makes warning signs and missing comparisons easier to ignore.', 'An emotional purchase can become an expensive regret.', 'Take a support person, sleep on it and walk away if checks are blocked.'],
  ['Failing to make a real budget', 'A budget shows whether the car fits with rent, school, savings and other priorities.', 'A manageable-looking repayment can still crowd out your life.', 'Test a realistic weekly or monthly budget before committing.'],
];

const covers = [
  { id: 'ctp', name: 'CTP / Green Slip', short: 'Required cover', colour: 'mint', description: 'Compulsory Third Party insurance helps cover injuries to people caused by a vehicle crash. It is required for registration, but it does not cover damage to cars or property.', yes: ['Injuries to other people', 'Registration requirement', 'State scheme rules'], no: ['Damage to your car', 'Theft or weather damage', 'Damage to another car'] },
  { id: 'third-party', name: 'Third Party Property Damage', short: 'Cover what you damage', colour: 'yellow', description: 'This cover helps pay for damage you cause to someone else’s vehicle or property. Your own vehicle is not covered.', yes: ['Damage to another person’s property', 'Legal liability within the policy', 'A lower-cost option for some older cars'], no: ['Repairs to your own car', 'Theft of your car', 'Storm or hail damage'] },
  { id: 'fire-theft', name: 'Third Party Fire & Theft', short: 'Add theft protection', colour: 'lilac', description: 'This cover includes Third Party Property Damage and adds protection if your car is stolen or damaged by fire, subject to policy terms and excess.', yes: ['Damage to another person’s property', 'Theft of your vehicle', 'Some fire-related damage'], no: ['Every crash to your own car', 'Wear and tear', 'Anything excluded by the policy'] },
  { id: 'comprehensive', name: 'Comprehensive', short: 'Widest protection', colour: 'blue', description: 'Comprehensive cover generally protects your car for covered crash damage, theft, fire, hail and storm, and includes liability for damage you cause to others.', yes: ['Damage to your car in a covered event', 'Damage to another person’s property', 'Theft, fire and weather events'], no: ['Regular maintenance or wear', 'Unlicensed or excluded driving', 'Anything outside the policy wording'] },
];

const sources = [
  ['NRMA Insurance — Car insurance', 'https://www.nrma.com.au/car-insurance', 'General insurance concepts and cover terminology.'],
  ['MoneySmart — Buying and managing a car', 'https://moneysmart.gov.au/buying-and-managing-a-car', 'Budgeting, finance and running-cost guidance.'],
  ['ACCC — Motor vehicle consumer guarantees', 'https://www.accc.gov.au/business/selling-products-and-services/consumer-guarantees/motor-vehicles', 'Dealer, consumer guarantee and remedy information.'],
  ['NSW Government — Buying and selling vehicles', 'https://www.nsw.gov.au/driving-boating-and-transport/vehicle-registration/buying-and-selling-vehicles', 'Registration and private-sale checks.'],
  ['ANCAP — Vehicle safety ratings', 'https://www.ancap.com.au/', 'The recommendation to compare independent safety ratings.'],
];

function Icon({ name, size = 24, strokeWidth = 2.2 }) {
  const p = { width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': 'true' };
  if (name === 'search') return <svg {...p}><circle cx="10.8" cy="10.8" r="6.7" /><path d="m16 16 5 5" /></svg>;
  if (name === 'user') return <svg {...p}><circle cx="12" cy="8" r="3.2" fill="currentColor" stroke="none" /><path d="M5.4 20c.7-3.3 3.1-5 6.6-5s5.9 1.7 6.6 5" fill="currentColor" stroke="none" /></svg>;
  if (name === 'chevron') return <svg {...p}><path d="m9 5 7 7-7 7" /></svg>;
  if (name === 'arrow-left') return <svg {...p}><path d="M19 12H5M11 18l-6-6 6-6" /></svg>;
  if (name === 'arrow-up-right' || name === 'external') return <svg {...p}><path d="M6 18 18 6M8 6h10v10" /></svg>;
  if (name === 'home') return <svg {...p}><path d="m3.5 10.5 8.5-7 8.5 7" /><path d="M5.5 9.5V20h13V9.5M9.5 20v-6h5v6" /></svg>;
  if (name === 'warning') return <svg {...p}><path d="m12 3 9 17H3L12 3Z" /><path d="M12 9v5M12 17h.01" /></svg>;
  if (name === 'cart') return <svg {...p}><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.2a2 2 0 0 0 1.9-1.4L20 8H6" /><circle cx="10" cy="20" r="1" /><circle cx="17" cy="20" r="1" /></svg>;
  if (name === 'shield') return <svg {...p}><path d="M12 3 20 6v5.8c0 4.8-3.3 7.8-8 9.2-4.7-1.4-8-4.4-8-9.2V6l8-3Z" /><path d="m8.5 12 2.3 2.3 4.8-5" /></svg>;
  if (name === 'document') return <svg {...p}><path d="M6 3.5h8l4 4V20.5H6z" /><path d="M14 3.5v4h4M9 12h6M9 16h6" /></svg>;
  if (name === 'book') return <svg {...p}><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21V5.5Z" /><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M8 7h8M8 11h8" /></svg>;
  if (name === 'car') return <svg {...p}><path d="m5 16-1-5 2-5h12l2 5-1 5M4 16h16v3H4z" /><circle cx="8" cy="15" r="1" fill="currentColor" /><circle cx="16" cy="15" r="1" fill="currentColor" /><path d="M7 6h10" /></svg>;
  if (name === 'tag') return <svg {...p}><path d="M4 5v6l9 9 7-7-9-9H4Z" /><circle cx="8" cy="9" r="1" /></svg>;
  if (name === 'fuel') return <svg {...p}><path d="M6 21V4h8v17M6 8h8M14 7h2l2 2v8.5a1.5 1.5 0 0 0 3 0V12l-2-2M9 6h2" /></svg>;
  if (name === 'check') return <svg {...p}><path d="m5 12 4 4L19 6" /></svg>;
  if (name === 'close') return <svg {...p}><path d="m6 6 12 12M18 6 6 18" /></svg>;
  if (name === 'wrench') return <svg {...p}><path d="M14.8 6.2a4.1 4.1 0 0 0-5.1 5.1L4 17a2.1 2.1 0 1 0 3 3l5.7-5.7a4.1 4.1 0 0 0 5.1-5.1l-2.4 2.4-2.8-.7-.7-2.8 2.9-1.9Z" /></svg>;
  if (name === 'copy') return <svg {...p}><rect x="8" y="8" width="11" height="11" rx="2" /><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2" /></svg>;
  if (name === 'briefcase') return <svg {...p}><rect x="3.5" y="7" width="17" height="12.5" rx="2" /><path d="M8 7V5.5A1.5 1.5 0 0 1 9.5 4h5A1.5 1.5 0 0 1 16 5.5V7M3.5 12h17M10 12v2h4v-2" /></svg>;
  if (name === 'plane') return <svg {...p}><path d="m3 12 18-7-5.2 7L21 19l-18-7Z" /><path d="m15.8 12-4.6 0M9.4 14.5 8 19" /></svg>;
  return <svg {...p}><circle cx="12" cy="12" r="8" /></svg>;
}

function InternalLink({ to, children, onNavigate, className = '', ...props }) {
  const click = (event) => { if (onNavigate && to.startsWith('/')) { event.preventDefault(); onNavigate(to); } };
  return <a href={to} className={className} onClick={click} {...props}>{children}</a>;
}

function Header({ path, resourceOpen, setResourceOpen, searchOpen, setSearchOpen, onNavigate, onAction }) {
  const guideActive = path.startsWith(GUIDE);
  return <header className="site-header">
    <div className="topbar"><div className="site-width topbar-inner">
      <InternalLink to="/" onNavigate={onNavigate} className="brand-link" aria-label="NRMA Insurance home"><img src="/assets/nrma-help-company-logo.png" alt="NRMA Insurance — A Help Company" /></InternalLink>
      <div className="header-actions"><button className="pill-button pill-button-primary" type="button" onClick={() => onAction('quote')}>Get a quote</button><button className="pill-button pill-button-outline" type="button" onClick={() => onAction('claim')}>Make a claim</button><button className="profile-button" type="button" aria-label="Account" onClick={() => onAction('account')}><Icon name="user" size={28} strokeWidth={1.8} /></button></div>
    </div></div>
    <div className="nav-row"><div className="site-width nav-inner">
      <nav className="main-nav" aria-label="Main navigation">
        {['Car & Vehicle', 'Home & Property', 'Business', 'Travel', 'Home Loans'].map((item) => <button type="button" className="nav-trigger" key={item} onClick={() => onAction('info')}>{item}</button>)}
        <button type="button" className={'nav-trigger resource-trigger' + (resourceOpen || guideActive ? ' is-active' : '')} onMouseEnter={() => { setResourceOpen(true); setSearchOpen(false); }} onFocus={() => { setResourceOpen(true); setSearchOpen(false); }} onClick={() => { setResourceOpen(true); setSearchOpen(false); }} aria-expanded={resourceOpen}>Resources</button>
      </nav>
      <button type="button" className={'search-trigger' + (searchOpen ? ' is-active' : '')} onMouseEnter={() => { setSearchOpen(true); setResourceOpen(false); }} onFocus={() => { setSearchOpen(true); setResourceOpen(false); }} onClick={() => { setSearchOpen(true); setResourceOpen(false); }} aria-expanded={searchOpen}><Icon name="search" size={30} strokeWidth={1.8} /><span>Search</span></button>
    </div></div>
    {resourceOpen && <MegaMenu onNavigate={onNavigate} />}
    {searchOpen && <SearchPopover onNavigate={onNavigate} />}
  </header>;
}

function MegaMenu({ onNavigate }) {
  return <div className="mega-menu" role="dialog" aria-label="Resources"><div className="site-width mega-menu-grid">
    <div className="mega-intro"><span className="mega-intro-kicker">NRMA Insurance</span><h2>First Car Guide</h2><p>Everything you need to make a confident first-car decision.</p></div>
    <div className="mega-column"><h3>First Car Guide <Icon name="chevron" size={21} /></h3><InternalLink to={GUIDE} onNavigate={onNavigate}>Home</InternalLink><InternalLink to={pagePath('mistakes')} onNavigate={onNavigate}>The Top 10 Mistakes</InternalLink><InternalLink to={pagePath('buying-smart')} onNavigate={onNavigate}>Buying Smart</InternalLink></div>
    <div className="mega-column"><h3>Protect your purchase <Icon name="chevron" size={21} /></h3><InternalLink to={pagePath('protect-yourself')} onNavigate={onNavigate}>Protect Yourself</InternalLink><InternalLink to={pagePath('insurance')} onNavigate={onNavigate}>Insurance Explained</InternalLink><InternalLink to={pagePath('sources')} onNavigate={onNavigate}>Sources &amp; Credits</InternalLink></div>
    <div className="mega-column"><h3>Quick links <Icon name="chevron" size={21} /></h3><a href="https://www.nrma.com.au/car-insurance" target="_blank" rel="noreferrer">Car insurance <Icon name="arrow-up-right" size={18} /></a><a href="https://moneysmart.gov.au/buying-and-managing-a-car" target="_blank" rel="noreferrer">MoneySmart car guide <Icon name="arrow-up-right" size={18} /></a><InternalLink to={pagePath('sources')} onNavigate={onNavigate}>Sources &amp; credits</InternalLink></div>
  </div></div>;
}

function SearchPopover({ onNavigate }) {
  const [query, setQuery] = useState('');
  const matching = pages.filter((page) => {
    const extra = page.slug === 'buying-smart' ? ' budget cost money running expenses' : page.slug === 'insurance' ? ' cover premium policy' : page.slug === 'protect-yourself' ? ' rights seller check' : '';
    return (page.title + ' ' + page.summary + extra).toLowerCase().includes(query.toLowerCase());
  });
  return <div className="search-popover"><div className="site-width search-popover-inner"><label htmlFor="site-search">Search this site</label><div className="search-field"><Icon name="search" size={22} /><input id="site-search" autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try “insurance” or “budget”" /></div><div className="search-results">{matching.map((page) => <InternalLink key={page.slug} to={pagePath(page.slug)} onNavigate={onNavigate}><span>{page.title}</span><Icon name="chevron" size={18} /></InternalLink>)}{matching.length === 0 && <p className="search-empty">No guide pages match that search.</p>}</div></div></div>;
}

function Home({ onNavigate, onAction }) {
  return <main className="home-main">
    <section className="home-hero"><div className="site-width home-hero-grid">
      <div className="trust-card"><div className="trust-copy"><span className="eyebrow eyebrow-light">NRMA Insurance</span><h1>Australia’s most trusted insurance brand, 4 years in a row</h1><p>We’re here to help protect the things you love, with cover that works for real life.</p><a className="text-link text-link-light" href="https://www.nrma.com.au/" target="_blank" rel="noreferrer">Why Australians trust NRMA <Icon name="chevron" size={18} /></a></div><div className="quote-card-grid"><QuoteCard icon="car" title="Car Insurance" onAction={onAction} /><QuoteCard icon="home" title="Home Insurance" onAction={onAction} /><QuoteCard icon="briefcase" title="Business Insurance" onAction={onAction} /><QuoteCard icon="document" title="CTP Green Slip" onAction={onAction} /></div></div>
      <div className="promo-stack"><Promo variant="green" eyebrow="Online offer" title="Get $150 off a new Comprehensive Car Insurance Policy" copy="Get a quote online and use code 150CAR." image="/assets/render-keyring.png" action="Get a quote" onAction={() => onAction('quote')} /><Promo variant="yellow" eyebrow="Save online" title="Get up to 10% off when you buy an eligible policy online" copy="Simple cover, helpful support and a little more value." image="/assets/render-terrace-house.png" action="Learn more" onAction={() => onAction('info')} /></div>
    </div></section>
    <section className="product-section"><div className="site-width"><div className="section-heading"><span className="eyebrow">Insurance for what matters</span><h2>Cover for every part of your life</h2><p>From your first car to the place you call home, explore insurance made for Australians.</p></div><div className="product-grid"><Product title="Car & Vehicle" icon="car" copy="Cover for cars, bikes, boats and more." onAction={onAction} /><Product title="Home & Property" icon="home" copy="Help protect your home and the things inside it." onAction={onAction} /><Product title="Business" icon="briefcase" copy="Flexible cover for the way you work." onAction={onAction} /><Product title="Travel" icon="plane" copy="Support for your next trip, close to home or far away." onAction={onAction} /></div><div className="guide-banner"><div><span className="eyebrow">For first-time car buyers</span><h3>Make your first car decision with confidence</h3><p>Explore the First Car Guide — a simple classroom resource for young Australians.</p></div><InternalLink to={GUIDE} onNavigate={onNavigate} className="outline-link">Open the guide <Icon name="chevron" size={18} /></InternalLink></div></div></section>
    <section className="customer-section"><div className="site-width"><div className="section-heading compact-heading"><span className="eyebrow">Already with us?</span><h2>We’re here when you need us</h2></div><div className="customer-actions"><button type="button" onClick={() => onAction('claim')}><Icon name="document" size={28} /><span><strong>Make a claim</strong><small>Start or track a claim</small></span><Icon name="chevron" size={21} /></button><button type="button" onClick={() => onAction('account')}><Icon name="user" size={28} /><span><strong>Manage your policy</strong><small>View your cover and documents</small></span><Icon name="chevron" size={21} /></button><a href="https://www.nrma.com.au/contact-us" target="_blank" rel="noreferrer"><Icon name="search" size={28} /><span><strong>Get help</strong><small>Find answers and contact options</small></span><Icon name="chevron" size={21} /></a></div></div></section>
    <section className="story-section"><div className="site-width"><div className="section-heading compact-heading"><span className="eyebrow">Helpful reads</span><h2>More from NRMA</h2></div><div className="story-grid"><Story to="https://www.nrma.com.au/blog" art="mint" title="How to choose your first car" label="On the road" external /><Story to="https://www.nrma.com.au/blog" art="yellow" title="What to check before you buy cover" label="Insurance basics" external /><Story to={pagePath('sources')} onNavigate={onNavigate} art="lilac" title="Explore our sources and credits" label="First Car Guide" /></div></div></section>
  </main>;
}

function QuoteCard({ icon, title, onAction }) { return <div className="quote-card"><Icon name={icon} size={42} strokeWidth={1.8} /><h2>{title}</h2><button type="button" onClick={() => onAction('quote')}>Get a quote</button></div>; }
function Promo({ variant, eyebrow, title, copy, image, action, onAction }) { return <article className={'promo-card promo-' + variant}><div className="promo-copy"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p><button type="button" className="promo-link" onClick={onAction}>{action} <Icon name="chevron" size={19} /></button></div><img src={image} alt="" /></article>; }
function Product({ title, icon, copy, onAction }) { return <article className="product-block"><div className="product-icon"><Icon name={icon} size={36} strokeWidth={1.8} /></div><h3>{title}</h3><p>{copy}</p><button type="button" onClick={() => onAction('info')}>Explore <Icon name="chevron" size={17} /></button></article>; }
function Story({ to, onNavigate, art, title, label, external }) { const C = external ? 'a' : InternalLink; const props = external ? { href: to, target: '_blank', rel: 'noreferrer' } : { to, onNavigate }; return <C className="story-card" {...props}><div className={'story-art story-art-' + art}><Icon name={art === 'mint' ? 'car' : art === 'yellow' ? 'shield' : 'book'} size={57} strokeWidth={1.5} /></div><div className="story-body"><span>{label}</span><h3>{title}</h3><Icon name={external ? 'arrow-up-right' : 'chevron'} size={19} /></div></C>; }

function Guide({ path, onNavigate }) {
  const slug = path === GUIDE || path === GUIDE + '/' ? 'home' : path.slice(GUIDE.length + 1).split('/')[0];
  if (slug === 'mistakes') return <Mistakes onNavigate={onNavigate} />;
  if (slug === 'buying-smart') return <BuyingSmart onNavigate={onNavigate} />;
  if (slug === 'protect-yourself') return <Protect onNavigate={onNavigate} />;
  if (slug === 'insurance') return <Insurance onNavigate={onNavigate} />;
  if (slug === 'sources') return <Sources onNavigate={onNavigate} />;
  return <GuideHome onNavigate={onNavigate} />;
}

function Shell({ page, onNavigate, children }) {
  return <main className="guide-main"><div className="site-width"><nav className="breadcrumbs" aria-label="Breadcrumb"><InternalLink to="/" onNavigate={onNavigate}>NRMA Insurance</InternalLink><Icon name="chevron" size={15} /><InternalLink to={GUIDE} onNavigate={onNavigate}>First Car Guide</InternalLink><Icon name="chevron" size={15} /><span>{page.title}</span></nav><div className="guide-layout"><div className="guide-content">{children}</div><Rail current={page.slug} onNavigate={onNavigate} /></div></div></main>;
}
function Title({ page, children }) { return <section className={'guide-title-card accent-' + page.accent}><div className="guide-title-icon"><Icon name={page.icon} size={36} strokeWidth={1.8} /></div><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{children || page.summary}</p></section>; }
function Rail({ current, onNavigate }) { return <aside className="guide-rail"><div className="rail-card rail-card-dark"><span className="eyebrow eyebrow-light">First Car Guide</span><h2>Start with a plan.</h2><p>Small checks now can save a lot of stress later.</p><InternalLink to={GUIDE} onNavigate={onNavigate} className="text-link text-link-light">Guide home <Icon name="chevron" size={17} /></InternalLink></div><div className="rail-nav"><span>Explore the guide</span>{pages.slice(1, 5).map((item) => <InternalLink key={item.slug} to={pagePath(item.slug)} onNavigate={onNavigate} className={current === item.slug ? 'is-current' : ''}><span>{item.title}</span><Icon name="chevron" size={17} /></InternalLink>)}</div><div className="rail-card rail-card-mint"><Icon name="wrench" size={29} /><h3>Keep your numbers handy</h3><p>Use the calculator on Buying Smart to test a realistic monthly budget.</p><InternalLink to={pagePath('buying-smart')} onNavigate={onNavigate} className="text-link text-link-dark">Try it now <Icon name="chevron" size={17} /></InternalLink></div></aside>; }

function GuideHome({ onNavigate }) {
  const page = pages[0];
  return <Shell page={page} onNavigate={onNavigate}><Title page={page}>Buying your first car is exciting. This guide helps you slow down, ask the right questions and make a decision that fits your life and your budget.</Title><section className="guide-intro"><div><span className="eyebrow">Welcome</span><h2>A better first-car decision starts here</h2><p>Whether you are saving for your first set of wheels or comparing a few listings, the best choice is one you can afford to buy, run and protect.</p><p>Use the guide to learn the common traps, map out the full cost and understand your rights before you hand over your money.</p></div><div className="number-panel"><span>The simple formula</span><strong>Research<br />+ budget<br />+ checks</strong><small>= more confidence</small></div></section><section className="hub-section"><div className="section-heading"><span className="eyebrow">Explore the guide</span><h2>Choose a topic</h2></div><div className="guide-card-grid">{pages.slice(1).map((item) => <InternalLink key={item.slug} to={pagePath(item.slug)} onNavigate={onNavigate} className={'guide-link-card accent-' + item.accent}><div className="guide-link-top"><Icon name={item.icon} size={27} strokeWidth={1.8} /><Icon name="chevron" size={21} /></div><span className="eyebrow">{item.eyebrow}</span><h3>{item.title}</h3><p>{item.summary}</p></InternalLink>)}</div></section><Callout tone="mint" title="If the deal feels rushed, pause." copy="You are allowed to ask questions, compare options and walk away." link={pagePath('protect-yourself')} linkText="Protect yourself" onNavigate={onNavigate} /></Shell>;
}

function Mistakes({ onNavigate }) {
  const page = pages[1]; const [open, setOpen] = useState(0);
  return <Shell page={page} onNavigate={onNavigate}><Title page={page}>A first car can be a great step towards independence. These are the ten mistakes most likely to make the decision more expensive or stressful.</Title><div className="content-intro-row"><p>Open each point to see what can go wrong and one practical way to avoid it.</p><span>10 checks to make</span></div><section className="accordion-list">{mistakes.map((item, index) => { const active = open === index; return <article className={'accordion-item' + (active ? ' is-open' : '')} key={item[0]}><button type="button" onClick={() => setOpen(active ? -1 : index)} aria-expanded={active}><span className="accordion-number">{String(index + 1).padStart(2, '0')}</span><strong>{item[0]}</strong><b>{active ? '−' : '+'}</b></button>{active && <div className="accordion-body"><div><strong>Why it happens</strong><p>{item[1]}</p></div><div><strong>What it can cost</strong><p>{item[2]}</p></div><div className="advice-box"><Icon name="check" size={19} /><span><strong>Practical advice</strong><p>{item[3]}</p></span></div></div>}</article>; })}</section><Callout tone="yellow" title="Turn the list into a real budget." copy="Buying Smart shows what the full cost can look like month to month." link={pagePath('buying-smart')} linkText="Buying Smart" onNavigate={onNavigate} /></Shell>;
}

function BuyingSmart({ onNavigate }) {
  const page = pages[2]; const [insurance, setInsurance] = useState(140); const [fuel, setFuel] = useState(180); const [registration, setRegistration] = useState(75); const [servicing, setServicing] = useState(80); const total = Number(insurance) + Number(fuel) + Number(registration) + Number(servicing);
  return <Shell page={page} onNavigate={onNavigate}><Title page={page}>The purchase price is only the beginning. Put every cost on the page so you can decide what is comfortable before you commit.</Title><section className="cost-section"><div className="section-heading"><span className="eyebrow">Your real budget</span><h2>Three layers of cost</h2></div><div className="cost-list"><Cost icon="tag" label="Initial costs" detail="Deposit, transfer, inspection, stamp duty and your first tank of fuel." value="$1,000+" width="72%" /><Cost icon="fuel" label="Ongoing costs" detail="Fuel, insurance, registration, servicing, tyres and repayments." value="Every month" width="92%" /><Cost icon="wrench" label="Hidden costs" detail="Parking, tolls, roadside help, unexpected repairs and upgrades." value="Keep a buffer" width="58%" /></div></section><section className="comparison-section"><div className="section-heading"><span className="eyebrow">Compare before you buy</span><h2>Where the money goes</h2></div><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Cost</th><th>When you pay</th><th>Question to ask</th></tr></thead><tbody><tr><td>Purchase price</td><td>Up front or over time</td><td>Is it within my total budget?</td></tr><tr><td>Insurance</td><td>Monthly or annually</td><td>What is the excess and what is excluded?</td></tr><tr><td>Registration &amp; CTP</td><td>At renewal</td><td>When is the next renewal due?</td></tr><tr><td>Fuel &amp; maintenance</td><td>Weekly and as needed</td><td>How much does this model use and cost to service?</td></tr></tbody></table></div></section><section className="calculator-section"><div className="calculator-copy"><span className="eyebrow">Interactive check</span><h2>Build a monthly estimate</h2><p>Move the numbers to see how a few running costs add up. It is a simple estimate, not a quote.</p><div className="calculator-total"><span>Estimated monthly running costs</span><strong>{'$' + total.toLocaleString('en-AU')}</strong></div></div><div className="calculator-controls"><Slider label="Insurance" value={insurance} onChange={setInsurance} min={50} max={350} step={10} /><Slider label="Fuel" value={fuel} onChange={setFuel} min={50} max={400} step={10} /><Slider label="Registration & CTP" value={registration} onChange={setRegistration} min={30} max={160} step={5} /><Slider label="Servicing buffer" value={servicing} onChange={setServicing} min={20} max={200} step={5} /></div></section><Callout tone="mint" title="Leave room for the unexpected." copy="A budget that only works on the perfect month is not a safe budget." link={pagePath('protect-yourself')} linkText="Protect yourself" onNavigate={onNavigate} /></Shell>;
}
function Cost({ icon, label, detail, value, width }) { return <div className="cost-row"><div className="cost-icon"><Icon name={icon} size={24} /></div><div className="cost-copy"><strong>{label}</strong><p>{detail}</p><div className="cost-bar"><span style={{ width }} /></div></div><span className="cost-value">{value}</span></div>; }
function Slider({ label, value, onChange, min, max, step }) { return <label className="budget-slider"><span><b>{label}</b><output>{'$' + Number(value).toLocaleString('en-AU')}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }

function Protect({ onNavigate }) {
  const page = pages[3]; const [checks, setChecks] = useState([false, false, false, false]); const items = ['Match the VIN with the paperwork', 'Run a PPSR vehicle history check', 'Book an independent inspection', 'Read the contract before paying']; const done = checks.filter(Boolean).length;
  return <Shell page={page} onNavigate={onNavigate}><Title page={page}>A careful buyer is not being difficult. They are checking that the car, the seller and the paperwork all make sense before money changes hands.</Title><section className="seller-section"><div className="section-heading"><span className="eyebrow">Know the difference</span><h2>Dealer or private seller?</h2></div><div className="seller-grid"><Seller title="Dealer" icon="shield" points={['Consumer guarantees may apply', 'Ask about the licence and paperwork', 'Get promises and faults in writing']} /><Seller title="Private seller" icon="user" points={['Protections can be more limited', 'Confirm the seller owns the vehicle', 'Never skip a history check or inspection']} /></div></section><section className="rights-section"><div><span className="eyebrow">Your consumer checklist</span><h2>Protect yourself before you pay</h2><p>Rules depend on where you live and whether you buy from a dealer or private seller. Read the contract carefully and seek advice if something does not feel right.</p><a className="text-link text-link-dark" href="https://www.accc.gov.au/business/selling-products-and-services/consumer-guarantees/motor-vehicles" target="_blank" rel="noreferrer">Read the ACCC guidance <Icon name="arrow-up-right" size={18} /></a></div><div className="checklist-card"><div className="checklist-heading"><strong>Ready-to-buy checklist</strong><span>{done}/4</span></div>{items.map((item, index) => <label key={item} className={checks[index] ? 'checked' : ''}><input type="checkbox" checked={checks[index]} onChange={() => setChecks((list) => list.map((v, i) => i === index ? !v : v))} /><span className="fake-checkbox"><Icon name="check" size={15} /></span><span>{item}</span></label>)}</div></section><div className="help-strip"><div className="help-strip-icon"><Icon name="wrench" size={31} /></div><div><span className="eyebrow">Need a second opinion?</span><h3>Talk to a trusted mechanic, family member or consumer adviser.</h3><p>A short pause can protect your savings and your safety.</p></div></div><Callout tone="blue" title="Choose cover that fits the risk." copy="Insurance Explained breaks down the options in plain language." link={pagePath('insurance')} linkText="Insurance Explained" onNavigate={onNavigate} /></Shell>;
}
function Seller({ title, icon, points }) { return <article className="seller-card"><div className="seller-icon"><Icon name={icon} size={28} /></div><h3>{title}</h3><ul>{points.map((point) => <li key={point}><Icon name="check" size={16} />{point}</li>)}</ul></article>; }

function Insurance({ onNavigate }) {
  const page = pages[4]; const [selected, setSelected] = useState('comprehensive'); const cover = covers.find((item) => item.id === selected) || covers[3];
  return <Shell page={page} onNavigate={onNavigate}><Title page={page}>Insurance can feel full of unfamiliar words. Start with what each type covers, then compare the price, excess and exclusions for your situation.</Title><section className="insurance-explorer"><div className="section-heading"><span className="eyebrow">Choose a cover type</span><h2>What protection do you need?</h2></div><div className="cover-tabs" role="tablist">{covers.map((item) => <button key={item.id} type="button" className={'cover-tab cover-tab-' + item.colour + (selected === item.id ? ' is-selected' : '')} onClick={() => setSelected(item.id)} role="tab" aria-selected={selected === item.id}><span>{item.name}</span><small>{item.short}</small></button>)}</div><div className={'cover-detail cover-detail-' + cover.colour}><div><span className="eyebrow">Selected cover</span><h3>{cover.name}</h3><p>{cover.description}</p></div><div className="cover-columns"><div><strong>Usually includes</strong><ul>{cover.yes.map((item) => <li key={item}><Icon name="check" size={16} />{item}</li>)}</ul></div><div><strong>Usually does not include</strong><ul>{cover.no.map((item) => <li key={item}><Icon name="close" size={16} />{item}</li>)}</ul></div></div></div></section><section className="premium-section"><div className="section-heading"><span className="eyebrow">Why prices differ</span><h2>What can affect a premium?</h2></div><div className="premium-grid"><Premium icon="car" title="The car" text="Make, model, age, safety features and repair costs can change the risk." /><Premium icon="user" title="The driver" text="Age, driving history, experience and who uses the car can affect the assessment." /><Premium icon="tag" title="The policy" text="Cover type, excess, agreed or market value and extras all matter." /><Premium icon="home" title="The location" text="Where the car is parked and how it is used can influence risk." /></div></section><Callout tone="peach" title="Cheapest is not always best value." copy="Compare what you would pay after an incident, not just the starting premium." link={pagePath('sources')} linkText="See the sources" onNavigate={onNavigate} /></Shell>;
}
function Premium({ icon, title, text }) { return <article className="premium-card"><div className="premium-icon"><Icon name={icon} size={26} /></div><h3>{title}</h3><p>{text}</p></article>; }

function Sources({ onNavigate }) {
  const page = pages[5];
  return <Shell page={page} onNavigate={onNavigate}><Title page={page}>This classroom website is designed to explain first-car decisions clearly. These official sources helped check the information and provide places to learn more.</Title><section className="sources-section"><div className="section-heading"><span className="eyebrow">Research trail</span><h2>Information sources</h2></div><div className="source-list">{sources.map((source, index) => <a key={source[1]} href={source[1]} target="_blank" rel="noreferrer" className="source-row"><span className="source-number">{String(index + 1).padStart(2, '0')}</span><span><strong>{source[0]}</strong><small>{source[2]}</small></span><Icon name="external" size={19} /></a>)}</div></section><section className="credits-panel"><div className="credits-icon"><Icon name="copy" size={31} /></div><div><span className="eyebrow">Visual credits</span><h2>About this project</h2><p>Created as a 9 Commerce Term 3 assessment. The layout is a student-made classroom interpretation inspired by the visual language of NRMA Insurance. NRMA’s logo, typography and selected imagery are reproduced for educational reference only; this project is not affiliated with or endorsed by NRMA Insurance.</p><p>Icons are inline SVGs created for this project. External links open in a new tab. Content should not replace professional financial, legal or insurance advice.</p></div></section><Callout tone="mint" title="Ready to make a plan?" copy="Use the guide home to jump to any topic." link={GUIDE} linkText="Guide home" onNavigate={onNavigate} /></Shell>;
}

function Callout({ tone, title, copy, link, linkText, onNavigate }) { return <div className={'guide-callout guide-callout-' + tone}><div><span className="eyebrow">Next step</span><h3>{title}</h3><p>{copy}</p></div><InternalLink to={link} onNavigate={onNavigate} className="navy-button">{linkText} <Icon name="chevron" size={18} /></InternalLink></div>; }

function Footer({ onNavigate }) {
  return <footer className="site-footer"><div className="site-width footer-top"><div className="footer-brand"><img src="/assets/nrma-help-company-logo.png" alt="NRMA Insurance — A Help Company" /><p>Protecting the things you love, and helping first-car buyers make informed choices.</p></div><div className="footer-column"><strong>Explore</strong><InternalLink to="/" onNavigate={onNavigate}>NRMA home</InternalLink><InternalLink to={GUIDE} onNavigate={onNavigate}>First Car Guide</InternalLink><InternalLink to={pagePath('sources')} onNavigate={onNavigate}>Sources &amp; credits</InternalLink></div><div className="footer-column"><strong>Useful links</strong><a href="https://www.nrma.com.au/car-insurance" target="_blank" rel="noreferrer">Car insurance</a><a href="https://moneysmart.gov.au/" target="_blank" rel="noreferrer">MoneySmart</a><a href="https://www.accc.gov.au/" target="_blank" rel="noreferrer">ACCC</a></div></div><div className="site-width footer-bottom"><span>Classroom project · 2026</span><span>Educational use only</span></div></footer>;
}

function Modal({ action, close }) {
  const [submitted, setSubmitted] = useState(false); const [choice, setChoice] = useState('Car');
  if (action === 'info') return <div className="modal-backdrop" onMouseDown={close}><div className="modal-card" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={close} aria-label="Close"><Icon name="close" size={22} /></button><span className="eyebrow">NRMA Insurance</span><h2>Here to help</h2><p>Explore the First Car Guide for an educational introduction to buying, budgeting and protecting your first car.</p><button type="button" className="navy-button modal-action" onClick={close}>Got it</button></div></div>;
  return <div className="modal-backdrop" onMouseDown={close}><div className="modal-card" onMouseDown={(event) => event.stopPropagation()}>{!submitted && <button className="modal-close" type="button" onClick={close} aria-label="Close"><Icon name="close" size={22} /></button>}{submitted ? <div className="modal-success"><div className="success-icon"><Icon name="check" size={34} /></div><span className="eyebrow">Thanks</span><h2>Your next step is ready.</h2><p>This demo keeps you on the classroom site. A real NRMA flow would continue securely from here.</p><button type="button" className="navy-button modal-action" onClick={close}>Close</button></div> : <><span className="eyebrow">A simple next step</span><h2>{action === 'claim' ? 'Make a claim' : action === 'account' ? 'Your NRMA account' : 'Get a quote'}</h2><p>{action === 'claim' ? 'Tell us what you need and we will show you where to start.' : action === 'account' ? 'This demo shows the interaction pattern for an account entry point.' : 'Choose what you are looking to protect to begin a sample quote.'}</p>{action === 'quote' && <label className="modal-select">I want a quote for<select value={choice} onChange={(event) => setChoice(event.target.value)}><option>Car</option><option>Home</option><option>Business</option><option>Travel</option></select></label>}<button type="button" className="navy-button modal-action" onClick={() => setSubmitted(true)}>Continue</button></>}</div></div>;
}

export default function App() {
  const [path, setPath] = useState(() => window.location.pathname);
  const [resourceOpen, setResourceOpen] = useState(() => window.location.pathname === '/');
  const [searchOpen, setSearchOpen] = useState(false);
  const [modal, setModal] = useState(null);
  useEffect(() => { const pop = () => { setPath(window.location.pathname); setResourceOpen(false); setSearchOpen(false); }; window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop); }, []);
  useEffect(() => { const active = pages.find((page) => pagePath(page.slug) === path); document.title = active ? active.title + ' | NRMA First Car Guide' : 'NRMA Insurance | First Car Guide'; window.scrollTo({ top: 0, behavior: 'auto' }); }, [path]);
  const navigate = (to) => { if (to === path) { setResourceOpen(false); return; } window.history.pushState({}, '', to); setPath(to); setResourceOpen(false); setSearchOpen(false); };
  const guideActive = path === GUIDE || path.startsWith(GUIDE + '/');
  return <div className="app"><Header path={path} resourceOpen={resourceOpen} setResourceOpen={setResourceOpen} searchOpen={searchOpen} setSearchOpen={setSearchOpen} onNavigate={navigate} onAction={setModal} />{guideActive ? <Guide path={path} onNavigate={navigate} /> : <Home onNavigate={navigate} onAction={setModal} />}<Footer onNavigate={navigate} />{modal && <Modal action={modal} close={() => setModal(null)} />}</div>;
}
